CREATE TABLE IF NOT EXISTS "public"."event_staff" (
  "id" bigint NOT NULL,
  "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
  "user_id" uuid NOT NULL,
  "event_id" bigint NOT NULL,
  "role" text
);

ALTER TABLE "public"."event_staff" OWNER TO "postgres";

ALTER TABLE "public"."event_staff" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME "public"."event_staff_id_seq"
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
);

ALTER TABLE ONLY "public"."event_staff"
  ADD CONSTRAINT "event_staff_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."event_staff"
  ADD CONSTRAINT "event_staff_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."event_staff"
  ADD CONSTRAINT "event_staff_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "event_staff_event_id_idx"
  ON "public"."event_staff" ("event_id");

CREATE INDEX IF NOT EXISTS "event_staff_user_id_idx"
  ON "public"."event_staff" ("user_id");

ALTER TABLE ONLY "public"."event_staff"
  ADD CONSTRAINT "event_staff_user_event_key" UNIQUE ("user_id", "event_id");

CREATE OR REPLACE TRIGGER "update_updated_at_event_staff"
  BEFORE UPDATE ON "public"."event_staff"
  FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

ALTER TABLE "public"."event_staff" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Can view event staff" ON "public"."event_staff" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Can insert event staff" ON "public"."event_staff" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Can update event staff" ON "public"."event_staff" FOR UPDATE TO "authenticated" USING (true);

CREATE POLICY "Can delete event staff" ON "public"."event_staff" FOR DELETE TO "authenticated" USING (true);
