CREATE TABLE IF NOT EXISTS "public"."communities" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "short_name" "text",
    "website" "text",
    "contact_email" "text" NOT NULL,
    "image" "text",
    "accepted" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."communities" OWNER TO "postgres";

ALTER TABLE "public"."communities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."communities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."calendar_events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "community_id" bigint NOT NULL,
    "start_datetime" timestamp with time zone NOT NULL,
    "end_datetime" timestamp with time zone NOT NULL,
    "format" "text",
    "registration_link" "text",
    "location" "text",
    "accepted" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."calendar_events" OWNER TO "postgres";

ALTER TABLE "public"."calendar_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."calendar_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."communities"
    ADD CONSTRAINT "communities_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."calendar_events"
    ADD CONSTRAINT "calendar_events_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."calendar_events"
    ADD CONSTRAINT "calendar_events_community_id_fkey" FOREIGN KEY ("community_id") REFERENCES "public"."communities"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "calendar_events_community_id_idx"
    ON "public"."calendar_events" ("community_id");

CREATE OR REPLACE TRIGGER "update_updated_at_communities"
    BEFORE UPDATE ON "public"."communities"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

CREATE OR REPLACE TRIGGER "update_updated_at_calendar_events"
    BEFORE UPDATE ON "public"."calendar_events"
    FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

ALTER TABLE "public"."communities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."calendar_events" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Can view accepted communities" ON "public"."communities" FOR SELECT TO "anon", "authenticated" USING ("accepted" OR "public"."is_admin"(auth.uid()));

CREATE POLICY "Can insert communities" ON "public"."communities" FOR INSERT TO "anon", "authenticated" WITH CHECK (NOT "accepted" OR "public"."is_admin"(auth.uid()));

CREATE POLICY "Can update communities" ON "public"."communities" FOR UPDATE TO "authenticated" USING ("public"."is_admin"(auth.uid()));

CREATE POLICY "Can delete communities" ON "public"."communities" FOR DELETE TO "authenticated" USING ("public"."is_admin"(auth.uid()));

CREATE POLICY "Can view accepted calendar events" ON "public"."calendar_events" FOR SELECT TO "anon", "authenticated" USING ("accepted" OR "public"."is_admin"(auth.uid()));

CREATE POLICY "Can insert calendar events" ON "public"."calendar_events" FOR INSERT TO "anon", "authenticated" WITH CHECK (NOT "accepted" OR "public"."is_admin"(auth.uid()));

CREATE POLICY "Can update calendar events" ON "public"."calendar_events" FOR UPDATE TO "authenticated" USING ("public"."is_admin"(auth.uid()));

CREATE POLICY "Can delete calendar events" ON "public"."calendar_events" FOR DELETE TO "authenticated" USING ("public"."is_admin"(auth.uid()));
